$ErrorActionPreference='Stop'
function Normalize-LfSha([string]$path){
  [byte[]]$bytes=[IO.File]::ReadAllBytes($path);$ms=New-Object IO.MemoryStream
  try{for($i=0;$i-lt$bytes.Length;$i++){if($bytes[$i]-eq13-and$i+1-lt$bytes.Length-and$bytes[$i+1]-eq10){continue};$ms.WriteByte($bytes[$i])};$norm=$ms.ToArray()}finally{$ms.Dispose()}
  $sha=[Security.Cryptography.SHA256]::Create();try{$digest=$sha.ComputeHash($norm)}finally{$sha.Dispose()};return ([BitConverter]::ToString($digest)).Replace('-','').ToLowerInvariant()
}
$subdir='ci/work/ETS2-Truck-Visual-Identifier-v2';$root=(Resolve-Path $subdir).Path

$patch=(Resolve-Path 'ci\msvc-c4505.patch').Path;$patchSha=(Get-FileHash $patch -Algorithm SHA256).Hash.ToLowerInvariant();$expectedPatch='a74bf770033ec4ef23ef514baea5734831eeb4103e7a0dbd216fdecacdcdea82'
if($patchSha-ne$expectedPatch){throw "MSVC patch SHA mismatch expected=$expectedPatch actual=$patchSha"}
$resultFile=Join-Path $root 'src\gui\windows_platform.cpp';$beforeSha=(Get-FileHash $resultFile -Algorithm SHA256).Hash.ToLowerInvariant();$expectedBefore='3ca9a55a0e50c05e036bae73621a90ee1df53e9c3ee2aa7ac4c364faabbfe3af'
if($beforeSha-ne$expectedBefore){throw "Pre-patch windows_platform.cpp SHA mismatch expected=$expectedBefore actual=$beforeSha"}
& git apply --check --whitespace=nowarn --directory=$subdir $patch;if($LASTEXITCODE-ne0){throw "git apply --check failed: $LASTEXITCODE"};& git apply --whitespace=nowarn --directory=$subdir $patch;if($LASTEXITCODE-ne0){throw "git apply failed: $LASTEXITCODE"}
$resultSha=(Get-FileHash $resultFile -Algorithm SHA256).Hash.ToLowerInvariant();$acceptedRaw=@('4defdba6b1c39cdcabac769bf0c7c3046886eaab2878889cbd654cd31f49da93','c486a039250b917ad83d74aafc718f19072d719221876f030fc903cc5de0a9d3');if($acceptedRaw-notcontains$resultSha){throw "Patched result SHA is not an audited LF/CRLF representation: $resultSha"}
$normalizedSha=Normalize-LfSha $resultFile;$expectedNormalized='4defdba6b1c39cdcabac769bf0c7c3046886eaab2878889cbd654cd31f49da93';if($normalizedSha-ne$expectedNormalized){throw "Patched normalized-LF SHA mismatch expected=$expectedNormalized actual=$normalizedSha"}

$vfsPatch=(Resolve-Path 'ci\windows-vfs-test-createprocess.patch').Path;$vfsPatchSha=(Get-FileHash $vfsPatch -Algorithm SHA256).Hash.ToLowerInvariant();$expectedVfsPatch='cc35f71ebf5992ab22b8bb78d3ad88e6d0a7ee9fe68f1b36af32b5f8941df58a'
if($vfsPatchSha-ne$expectedVfsPatch){throw "VFS test patch SHA mismatch expected=$expectedVfsPatch actual=$vfsPatchSha"}
$vfsFile=Join-Path $root 'src\gui\windows_integration_tests.cpp';$vfsBefore=(Get-FileHash $vfsFile -Algorithm SHA256).Hash.ToLowerInvariant();$expectedVfsBefore='3193b50ce9dbbb62280101243dfe12d0fb7e60ec29a8de01f6f05cdd1b64a578';if($vfsBefore-ne$expectedVfsBefore){throw "Pre-patch windows_integration_tests.cpp SHA mismatch expected=$expectedVfsBefore actual=$vfsBefore"}
& git apply --check --whitespace=nowarn --directory=$subdir $vfsPatch;if($LASTEXITCODE-ne0){throw "VFS test git apply --check failed: $LASTEXITCODE"};& git apply --whitespace=nowarn --directory=$subdir $vfsPatch;if($LASTEXITCODE-ne0){throw "VFS test git apply failed: $LASTEXITCODE"}
$vfsResult=(Get-FileHash $vfsFile -Algorithm SHA256).Hash.ToLowerInvariant();$acceptedVfsRaw=@('805a3b4b2f14b087db3a5ca5fe534b19b8f5ef4bc889b05aa41fb74f786368e6','98b6131f00fdf8b56d8b0614eadc11cfe10c04c15da3a621a21d6e725ee99553');if($acceptedVfsRaw-notcontains$vfsResult){throw "VFS test patched result SHA is not an audited LF/CRLF representation: $vfsResult"}
$vfsNormalized=Normalize-LfSha $vfsFile;$expectedVfsNormalized='805a3b4b2f14b087db3a5ca5fe534b19b8f5ef4bc889b05aa41fb74f786368e6';if($vfsNormalized-ne$expectedVfsNormalized){throw "VFS test normalized-LF SHA mismatch expected=$expectedVfsNormalized actual=$vfsNormalized"}

$readmePatch=(Resolve-Path 'ci\readme-utf8-packaging.patch').Path;$readmePatchSha=(Get-FileHash $readmePatch -Algorithm SHA256).Hash.ToLowerInvariant();$expectedReadmePatch='fd428f7ad7b9fb2048ea0073666d7f3c51d40d75fa6403219a4567cfc32ccac6'
if($readmePatchSha-ne$expectedReadmePatch){throw "README packaging patch SHA mismatch expected=$expectedReadmePatch actual=$readmePatchSha"}
$buildScript=Join-Path $root 'tools\build-windows.ps1';$buildBefore=(Get-FileHash $buildScript -Algorithm SHA256).Hash.ToLowerInvariant();$expectedBuildBefore='12e506e17fc3eb49a7e6180b292fee3e4e2e0386e5f038aaaf2d11041883767e';if($buildBefore-ne$expectedBuildBefore){throw "Pre-patch build-windows.ps1 SHA mismatch expected=$expectedBuildBefore actual=$buildBefore"}
& git apply --check --whitespace=nowarn --directory=$subdir $readmePatch;if($LASTEXITCODE-ne0){throw "README packaging git apply --check failed: $LASTEXITCODE"};& git apply --whitespace=nowarn --directory=$subdir $readmePatch;if($LASTEXITCODE-ne0){throw "README packaging git apply failed: $LASTEXITCODE"}
$buildResult=(Get-FileHash $buildScript -Algorithm SHA256).Hash.ToLowerInvariant();$acceptedBuildRaw=@('38904304a5452db02c37f4cbbdbd7ac952e36461d6e3cf1520d3b2f5f9be911b','6b349bf33312c062b4ee35bffab45eb2f2393232c272ddc6c2bfc0c4c73273eb');if($acceptedBuildRaw-notcontains$buildResult){throw "README packaging patched result SHA is not an audited LF/CRLF representation: $buildResult"}
$buildNormalized=Normalize-LfSha $buildScript;$expectedBuildNormalized='38904304a5452db02c37f4cbbdbd7ac952e36461d6e3cf1520d3b2f5f9be911b';if($buildNormalized-ne$expectedBuildNormalized){throw "README packaging normalized-LF SHA mismatch expected=$expectedBuildNormalized actual=$buildNormalized"}

$identity="BASE=$env:SOURCE_SHA256`nPATCH1=$patchSha`nNORMALIZED_RESULT1=$normalizedSha`nPATCH2=$vfsPatchSha`nNORMALIZED_RESULT2=$vfsNormalized`nPATCH3=$readmePatchSha`nNORMALIZED_RESULT3=$buildNormalized`n"
$sha=[Security.Cryptography.SHA256]::Create();try{$digest=$sha.ComputeHash([Text.Encoding]::ASCII.GetBytes($identity))}finally{$sha.Dispose()};$effective=([BitConverter]::ToString($digest)).Replace('-','').ToLowerInvariant();$expectedEffective='089901fc48d9460a48cb4965fca13f0a1e3de9dbe988e09782083efab461e74d';if($effective-ne$expectedEffective){throw "Effective source identity mismatch expected=$expectedEffective actual=$effective"}
Add-Content $env:GITHUB_ENV "BUILD_FIX_PATCH_SHA256=$patchSha";Add-Content $env:GITHUB_ENV "WINDOWS_VFS_TEST_PATCH_SHA256=$vfsPatchSha";Add-Content $env:GITHUB_ENV "README_UTF8_PATCH_SHA256=$readmePatchSha";Add-Content $env:GITHUB_ENV "EFFECTIVE_SOURCE_ID=$effective"
Add-Content -Encoding ASCII 'ci\SOURCE_PROVENANCE.txt' "BUILD_FIX_PATCH_SHA256=$patchSha";Add-Content -Encoding ASCII 'ci\SOURCE_PROVENANCE.txt' "RESULT_WINDOWS_PLATFORM_SHA256=$resultSha";Add-Content -Encoding ASCII 'ci\SOURCE_PROVENANCE.txt' "RESULT_WINDOWS_PLATFORM_NORMALIZED_LF_SHA256=$normalizedSha";Add-Content -Encoding ASCII 'ci\SOURCE_PROVENANCE.txt' "WINDOWS_VFS_TEST_PATCH_SHA256=$vfsPatchSha";Add-Content -Encoding ASCII 'ci\SOURCE_PROVENANCE.txt' "RESULT_WINDOWS_VFS_TEST_NORMALIZED_LF_SHA256=$vfsNormalized";Add-Content -Encoding ASCII 'ci\SOURCE_PROVENANCE.txt' "README_UTF8_PATCH_SHA256=$readmePatchSha";Add-Content -Encoding ASCII 'ci\SOURCE_PROVENANCE.txt' "RESULT_BUILD_WINDOWS_NORMALIZED_LF_SHA256=$buildNormalized";Add-Content -Encoding ASCII 'ci\SOURCE_PROVENANCE.txt' "EFFECTIVE_SOURCE_ID=$effective"
Write-Host "BUILD_FIX_PATCH_SHA256=$patchSha";Write-Host "WINDOWS_VFS_TEST_PATCH_SHA256=$vfsPatchSha";Write-Host "README_UTF8_PATCH_SHA256=$readmePatchSha";Write-Host "EFFECTIVE_SOURCE_ID=$effective"
