$ErrorActionPreference='Stop'
$root=(Resolve-Path 'ci\work\ETS2-Truck-Visual-Identifier-v2').Path
$exe=Join-Path $root 'build-win\src\gui\Release\ETS2TruckVisualIdentifier.exe';$dll=Join-Path $root 'build-win\src\plugin\Release\ets2_truck_visual_identifier.dll';$tool=Join-Path $root 'third_party\scs_tool\scs_tool.exe'
$dist=Join-Path $root 'dist';$pkg=Join-Path $dist 'ETS2_Truck_Visual_Identifier_CabinPaint_TEST_x64';$zip=Join-Path $dist 'ETS2_Truck_Visual_Identifier_CabinPaint_TEST_x64.zip';$report=Join-Path $dist 'BUILD_REPORT.txt'
foreach($p in @($exe,$dll,$tool,$pkg,$zip,$report)){if(-not(Test-Path $p)){throw "Missing required output: $p"}}
function Pe([string]$p){[byte[]]$b=[IO.File]::ReadAllBytes($p);if($b.Length-lt512-or$b[0]-ne0x4d-or$b[1]-ne0x5a){throw "Invalid MZ: $p"};$o=[BitConverter]::ToInt32($b,0x3c);if($o-lt0-or$o+96-ge$b.Length-or$b[$o]-ne0x50-or$b[$o+1]-ne0x45){throw "Invalid/truncated PE: $p"};$opt=$o+24;[pscustomobject]@{Machine=[BitConverter]::ToUInt16($b,$o+4);Magic=[BitConverter]::ToUInt16($b,$opt);Entry=[BitConverter]::ToUInt32($b,$opt+16);Subsystem=[BitConverter]::ToUInt16($b,$opt+68)}}
$ei=Pe $exe;$di=Pe $dll;$ti=Pe $tool;foreach($x in @(@('EXE',$ei),@('PLUGIN',$di),@('SCS_TOOL',$ti))){if($x[1].Magic-ne0x20b-or$x[1].Machine-ne0x8664-or$x[1].Entry-eq0){throw "$($x[0]) is not valid AMD64 PE32+"}};if($ei.Subsystem-ne2){throw 'GUI subsystem is not Windows GUI.'}
$vswhere=Join-Path ${env:ProgramFiles(x86)} 'Microsoft Visual Studio\Installer\vswhere.exe';$vs=(& $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath).Trim();if(-not$vs){throw 'Visual Studio not found.'};$dumpbin=Get-ChildItem (Join-Path $vs 'VC\Tools\MSVC\*\bin\Hostx64\x64\dumpbin.exe')|Sort-Object FullName -Descending|Select-Object -First 1 -ExpandProperty FullName
foreach($p in @($exe,$dll)){$deps=(& $dumpbin /DEPENDENTS $p 2>&1|Out-String);if($LASTEXITCODE-ne0){throw "dumpbin failed: $p"};if($deps-match'(?i)(msvcp[^ \r\n]*\.dll|vcruntime[^ \r\n]*\.dll|ucrtbased\.dll)'){throw "Unexpected dynamic/debug MSVC CRT: $p"}}
$exports=(& $dumpbin /EXPORTS $dll 2>&1|Out-String);if($LASTEXITCODE-ne0){throw 'Plugin export audit failed.'};foreach($n in @('scs_telemetry_init','scs_telemetry_shutdown')){if($exports-notmatch[regex]::Escape($n)){throw "Missing plugin export: $n"}}
if(-not('Ets2ViNative'-as[type])){Add-Type @'
using System; using System.Runtime.InteropServices;
public static class Ets2ViNative {
  [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)] public static extern IntPtr LoadLibraryW(string path);
  [DllImport("kernel32.dll")] public static extern bool FreeLibrary(IntPtr h);
  [DllImport("user32.dll",SetLastError=true)] public static extern IntPtr SendMessageTimeoutW(IntPtr hWnd,uint Msg,UIntPtr wParam,IntPtr lParam,uint flags,uint timeout,out UIntPtr result);
  [DllImport("user32.dll",SetLastError=true)] public static extern bool PostMessageW(IntPtr hWnd,uint Msg,UIntPtr wParam,IntPtr lParam);
}
'@}
$h=[Ets2ViNative]::LoadLibraryW($dll);if($h-eq[IntPtr]::Zero){throw "Plugin LoadLibraryW failed: $([Runtime.InteropServices.Marshal]::GetLastWin32Error())"};[void][Ets2ViNative]::FreeLibrary($h)
function Has([byte[]]$h,[byte[]]$n){for($i=0;$i-le$h.Length-$n.Length;$i++){$ok=$true;for($j=0;$j-lt$n.Length;$j++){if($h[$i+$j]-ne$n[$j]){$ok=$false;break}};if($ok){return $true}};return $false}
$install='Instala'+[char]0x00E7+[char]0x00E3+'o:';$truck='Caminh'+[char]0x00E3+'o:';$nao='N'+[char]0x00C3+'O INSTALADO';$title='ETS2 TRUCK VISUAL IDENTIFIER '+[char]0x2014+' TRACTOR ONLY';[byte[]]$eb=[IO.File]::ReadAllBytes($exe)
foreach($s in @($install,$truck,$nao,'IDENTIFICANDO...','Desconhecido',$title)){if(-not(Has $eb ([Text.Encoding]::Unicode.GetBytes($s)))){throw "UTF-16 UI string missing: $s"}}
foreach($s in @('Instala'+[char]0x00C3+[char]0x00A7,'Caminh'+[char]0x00C3+[char]0x00A3,[string][char]0xFFFD)){if(Has $eb ([Text.Encoding]::Unicode.GetBytes($s))){throw 'Mojibake/replacement sequence embedded in EXE.'}}
$proc=Start-Process -FilePath $exe -PassThru;try{if(-not$proc.WaitForInputIdle(5000)){throw 'GUI did not reach input-idle.'};Start-Sleep -Milliseconds 1000;$proc.Refresh();if($proc.HasExited){throw "GUI immediate crash: $($proc.ExitCode)"};if($proc.MainWindowTitle-ne$title){throw "Unexpected title: $($proc.MainWindowTitle)"};[UIntPtr]$r=[UIntPtr]::Zero;$ok=[Ets2ViNative]::SendMessageTimeoutW($proc.MainWindowHandle,0,[UIntPtr]::Zero,[IntPtr]::Zero,2,1000,[ref]$r);if($ok-eq[IntPtr]::Zero){throw 'GUI not responsive.'};if(-not[Ets2ViNative]::PostMessageW($proc.MainWindowHandle,0x0010,[UIntPtr]::Zero,[IntPtr]::Zero)){throw 'WM_CLOSE failed.'};if(-not$proc.WaitForExit(5000)){throw 'GUI did not exit cleanly.'};if($proc.ExitCode-ne0){throw "GUI exit=$($proc.ExitCode)"}}finally{if($proc-and-not$proc.HasExited){Stop-Process -Id $proc.Id -Force}}

$allowed=@('ETS2TruckVisualIdentifier.exe','README.txt','SHA256SUMS.txt','THIRD_PARTY_NOTICES.md','Runtime/ets2_truck_visual_identifier.dll','Runtime/scs_tool.exe')
$actual=Get-ChildItem $pkg -Recurse -File|ForEach-Object{$_.FullName.Substring($pkg.Length).TrimStart([char]92).Replace('\','/')};foreach($a in $allowed){if($actual-notcontains$a){throw "Package missing: $a"}};foreach($a in $actual){if($allowed-notcontains$a){throw "Unexpected package file: $a"}}
$forbidden=Get-ChildItem $pkg -Recurse -File|Where-Object{$_.Extension-in@('.obj','.pdb','.lib','.exp','.ilk','.cpp','.h','.hpp','.ps1','.vcxproj','.sln')};if($forbidden){throw "Forbidden package artifact: $($forbidden.FullName -join ', ')"}

$audit=Join-Path $env:RUNNER_TEMP 'ets2-final-zip-audit';if(Test-Path $audit){Remove-Item $audit -Recurse -Force};New-Item -ItemType Directory -Force $audit|Out-Null;Expand-Archive -LiteralPath $zip -DestinationPath $audit -Force
$zipPkg=Join-Path $audit 'ETS2_Truck_Visual_Identifier_CabinPaint_TEST_x64';if(-not(Test-Path $zipPkg)){throw "ZIP package root missing: $zipPkg"}
$zipActual=Get-ChildItem $zipPkg -Recurse -File|ForEach-Object{$_.FullName.Substring($zipPkg.Length).TrimStart([char]92).Replace('\','/')};foreach($a in $allowed){if($zipActual-notcontains$a){throw "ZIP missing: $a"}};foreach($a in $zipActual){if($allowed-notcontains$a){throw "ZIP unexpected file: $a"}}
$strictUtf8=[Text.UTF8Encoding]::new($false,$true);$decoded=@{}
foreach($rel in @('README.txt','SHA256SUMS.txt','THIRD_PARTY_NOTICES.md')){
  $path=Join-Path $zipPkg $rel;try{$text=$strictUtf8.GetString([IO.File]::ReadAllBytes($path))}catch{throw "ZIP text not strict UTF-8: ${rel}: $($_.Exception.Message)"};$decoded[$rel]=$text
  $genericBad=@(([string][char]0xFFFD),([string][char]0x00C3+[char]0x00A7),([string][char]0x00C3+[char]0x00A3),([string][char]0x00C3+[char]0x00A9),([string][char]0x00C3+[char]0x00B3),([string][char]0x00C3+[char]0x00BA),([string][char]0x00C3+[char]0x00AA),([string][char]0x00C3+[char]0x00B4),([string][char]0x00C3+[char]0x0192));foreach($bad in $genericBad){if($text.Contains($bad)){throw "ZIP mojibake pattern detected in ${rel}: $bad"}}
}
$lowerATilde=[char]0x00E3;$cCed=[char]0x00E7;$oAcute=[char]0x00F3;$readme=$decoded['README.txt']
foreach($m in @(('identifica'+$cCed+$lowerATilde+'o'),('caminh'+$lowerATilde+'o'),('atualiza'+$cCed+$lowerATilde+'o'),('diagn'+$oAcute+'stico'),'TruckVisualIdentity.log')){if(-not$readme.Contains($m)){throw "ZIP README UTF-8 marker missing: $m"}}
foreach($bad in @(('caminh'+[char]0x00C3+'o'),('identifica'+[char]0x00E7+[char]0x00C3+'o'))){if($readme.Contains($bad)){throw "ZIP README mojibake detected: $bad"}}
$sumPath=Join-Path $zipPkg 'SHA256SUMS.txt';$sumLines=@(Get-Content $sumPath -Encoding ASCII|Where-Object{$_ -ne ''});$seen=@{}
foreach($line in $sumLines){if($line-notmatch'^([0-9a-f]{64})  (.+)$'){throw "Malformed ZIP SHA256SUMS line: $line"};$expected=$matches[1];$rel=$matches[2].Replace('/','\');if($seen.ContainsKey($rel)){throw "Duplicate ZIP SHA entry: $rel"};$seen[$rel]=$true;$file=Join-Path $zipPkg $rel;if(-not(Test-Path $file)){throw "ZIP SHA target missing: $rel"};$actualHash=(Get-FileHash $file -Algorithm SHA256).Hash.ToLowerInvariant();if($actualHash-ne$expected){throw "ZIP SHA mismatch for $rel expected=$expected actual=$actualHash"}}
foreach($rel in @('ETS2TruckVisualIdentifier.exe','README.txt','THIRD_PARTY_NOTICES.md','Runtime\ets2_truck_visual_identifier.dll','Runtime\scs_tool.exe')){if(-not$seen.ContainsKey($rel)){throw "ZIP SHA manifest missing: $rel"}};if($seen.Count-ne5){throw "Unexpected ZIP SHA manifest count: $($seen.Count)"}
$reportText=Get-Content $report -Raw -Encoding ASCII;foreach($marker in @('POST-PACKAGE README UTF-8 AUDIT: PASS','POST-PACKAGE FILE AUDIT: PASS','FINAL_ZIP_SHA256=')){if(-not$reportText.Contains($marker)){throw "Build report missing post-package marker: $marker"}}
$finalZipSha=(Get-FileHash $zip -Algorithm SHA256).Hash.ToLowerInvariant();if($reportText-notmatch("FINAL_ZIP_SHA256="+[regex]::Escape($finalZipSha))){throw "Build report final ZIP SHA mismatch: $finalZipSha"}
Add-Content -Encoding ASCII $report "SOURCE_ARCHIVE_SHA256=$env:SOURCE_SHA256";Add-Content -Encoding ASCII $report "BUILD_FIX_PATCH_SHA256=$env:BUILD_FIX_PATCH_SHA256";Add-Content -Encoding ASCII $report "WINDOWS_VFS_TEST_PATCH_SHA256=$env:WINDOWS_VFS_TEST_PATCH_SHA256";Add-Content -Encoding ASCII $report "README_UTF8_PATCH_SHA256=$env:README_UTF8_PATCH_SHA256";Add-Content -Encoding ASCII $report "EFFECTIVE_SOURCE_ID=$env:EFFECTIVE_SOURCE_ID";Add-Content -Encoding ASCII $report "BRANCH=$env:SOURCE_BRANCH";Add-Content -Encoding ASCII $report "COMMIT=$env:SOURCE_COMMIT";Add-Content -Encoding ASCII $report 'WINDOWS HASHFS/VFS TEST: PASS (ctest)';Add-Content -Encoding ASCII $report 'CABIN/PAINT WINDOWS TESTS: PASS (ctest)';Add-Content -Encoding ASCII $report 'UNINSTALL WINDOWS TEST: PASS';Add-Content -Encoding ASCII $report 'FINAL PE AUDIT: PASS';Add-Content -Encoding ASCII $report 'WINDOWS GUI SMOKE TEST: PASS';Add-Content -Encoding ASCII $report 'PACKAGE AUDIT: PASS';Add-Content -Encoding ASCII $report 'README UTF-8 AUDIT: PASS';Add-Content -Encoding ASCII $report 'INDEPENDENT POST-PACKAGE AUDIT: PASS'
Copy-Item 'ci\SOURCE_PROVENANCE.txt' (Join-Path $dist 'SOURCE_PROVENANCE.txt') -Force
$releaseState=Join-Path $dist 'RELEASE_STATE.txt';@('STATE=READY_FOR_USER_TEST',"FINAL_ZIP_NAME=$(Split-Path $zip -Leaf)","FINAL_ZIP_SHA256=$finalZipSha","SOURCE_COMMIT=$env:SOURCE_COMMIT","SOURCE_SNAPSHOT_SHA256=$env:SOURCE_SHA256","WORKFLOW_RUN_ID=$env:GITHUB_RUN_ID",'REAL_ETS2_CABIN=PENDING_USER_TEST','REAL_ETS2_COLOR=PENDING_USER_TEST','REAL_ETS2_PAINT=PENDING_USER_TEST')|Set-Content -Encoding ASCII $releaseState
Add-Content -Encoding ASCII (Join-Path $dist 'SOURCE_PROVENANCE.txt') "WORKFLOW_RUN_ID=$env:GITHUB_RUN_ID";Add-Content -Encoding ASCII (Join-Path $dist 'SOURCE_PROVENANCE.txt') "FINAL_ZIP_SHA256=$finalZipSha"
Write-Host "FINAL_ZIP_SHA256=$finalZipSha";Write-Host 'RELEASE_STATE=READY_FOR_USER_TEST'
